[project]
name = "glutenfreebakery"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "attrs >=25.1.0, <26",
    "numpy >=2.0, <3",
]


[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "basedpyright",
]

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.coverage.report]
exclude_also = [
    "\\s+\\.\\.\\.",
]
